const loggerActionTypes = {
    SCAN_LOGGER: 'SCAN_LOGGER',
    TOGGLE_LOADING:'TOGGLE_LOADING',
    TOGGLE_DISPATCH:'TOGGLE_DISPATCH',
    TOGGLE_DODO:'TOGGLE_DODO',
    TOGGLE_BAORDER:'TOGGLE_BAORDER',
    TOGGLE_SDS:'TOGGLE_SDS'
  };
  
  export default loggerActionTypes;